#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d I II III IV V VI VII VIII 

export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width         2
bspc config window_gap           4
bspc config border_radius	 6

bspc config active_border_color \#BA55D3
bspc config normal_border_color \#D8BFD8
bspc config focused_border_color \#FF00FF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'

